Repository Tough-Guy-Money-Party/Crayon-BE, pull requests merged in 2025-06, with the labels that each got.

#393 CRA-162 외부 지원서 가져오기
  .github/workflows/dev.yml
  .github/workflows/main.yml
  src/main/java/com/yoyomo/domain/application/application/dto/request/ApplicationImportRequest.java
  src/main/java/com/yoyomo/domain/application/application/dto/request/DataRequest.java
  src/main/java/com/yoyomo/domain/application/application/dto/request/QuestionRequest.java
  src/main/java/com/yoyomo/domain/application/application/dto/request/RespondentRequest.java
  src/main/java/com/yoyomo/domain/application/application/usecase/ApplicationImportUseCase.java
  src/main/java/com/yoyomo/domain/application/domain/entity/Application.java
  src/main/java/com/yoyomo/domain/application/domain/model/Applicant.java
  src/main/java/com/yoyomo/domain/application/domain/model/ApplicantInfo.java
  src/main/java/com/yoyomo/domain/application/domain/model/ApplicantReply.java
  src/main/java/com/yoyomo/domain/application/domain/model/Question.java
  src/main/java/com/yoyomo/domain/application/domain/model/QuestionReply.java
  src/main/java/com/yoyomo/domain/application/domain/model/Replies.java
  src/main/java/com/yoyomo/domain/application/domain/model/Reply.java
  src/main/java/com/yoyomo/domain/application/domain/repository/ApplicationJdbcRepository.java
  src/main/java/com/yoyomo/domain/application/domain/service/AnswerSaveService.java
  src/main/java/com/yoyomo/domain/application/domain/service/ApplicationSaveService.java
  src/main/java/com/yoyomo/domain/application/exception/BatchInsertFailException.java
  src/main/java/com/yoyomo/domain/application/exception/InvalidApplicantInfoException.java
  src/main/java/com/yoyomo/domain/application/exception/InvalidDateFormat.java
  src/main/java/com/yoyomo/domain/application/exception/QuestionReplySizeMismatchException.java
  src/main/java/com/yoyomo/domain/application/presentation/ApplicationController.java
  src/main/java/com/yoyomo/domain/application/presentation/constant/ResponseMessage.java
  src/main/java/com/yoyomo/domain/item/domain/entity/Answer.java
  src/main/java/com/yoyomo/domain/item/domain/service/factory/AnswerCreationStrategy.java
  src/main/java/com/yoyomo/domain/item/domain/service/factory/ItemFactory.java
  src/main/java/com/yoyomo/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/resources/application-local.yml
  src/test/java/com/yoyomo/domain/application/application/usecase/ApplicationImportUseCaseTest.java
  src/test/java/com/yoyomo/domain/fixture/CustomRepository.java
  src/test/java/com/yoyomo/domain/fixture/TestFixture.java
  src/test/resources/application-test.properties
Labels: ✨ Feature

#394 CRA-163 지원서 매핑 DTO에서 수행
  src/main/java/com/yoyomo/domain/application/application/dto/request/ApplicationImportRequest.java
  src/main/java/com/yoyomo/domain/application/application/dto/request/DataRequest.java
  src/main/java/com/yoyomo/domain/application/application/dto/request/RespondentRequest.java
  src/main/java/com/yoyomo/domain/application/application/usecase/ApplicationImportUseCase.java
  src/main/java/com/yoyomo/domain/application/domain/model/ApplicantReply.java
  src/main/java/com/yoyomo/domain/application/domain/service/AnswerSaveService.java
  src/main/java/com/yoyomo/domain/application/domain/service/ApplicationSaveService.java
  src/main/java/com/yoyomo/domain/application/domain/vo/Applicant.java
  src/main/java/com/yoyomo/domain/application/domain/vo/ApplicantInfo.java
  src/main/java/com/yoyomo/domain/application/domain/vo/ApplicationReply.java
  src/main/java/com/yoyomo/domain/application/domain/vo/Question.java
  src/main/java/com/yoyomo/domain/application/domain/vo/QuestionCategory.java
  src/main/java/com/yoyomo/domain/application/domain/vo/QuestionReply.java
  src/main/java/com/yoyomo/domain/application/domain/vo/Replies.java
  src/main/java/com/yoyomo/domain/application/domain/vo/Reply.java
  src/main/java/com/yoyomo/domain/application/exception/ApplicationReplySizeMismatchException.java
  src/main/java/com/yoyomo/domain/application/presentation/constant/ResponseMessage.java
  src/main/java/com/yoyomo/domain/item/domain/service/factory/AnswerCreationStrategy.java
  src/main/java/com/yoyomo/domain/item/domain/service/factory/ItemFactory.java
Labels: 🛠️ Refactor

#395 DataType 추가 및 테스트 작성
  src/main/java/com/yoyomo/domain/application/application/dto/request/ApplicationImportRequest.java
  src/main/java/com/yoyomo/domain/application/application/dto/request/DataRequest.java
  src/main/java/com/yoyomo/domain/application/application/dto/request/RespondentRequest.java
  src/main/java/com/yoyomo/domain/application/domain/vo/DataType.java
  src/main/java/com/yoyomo/domain/application/domain/vo/Question.java
  src/main/java/com/yoyomo/domain/application/domain/vo/QuestionReply.java
  src/main/java/com/yoyomo/domain/application/domain/vo/Reply.java
  src/main/java/com/yoyomo/domain/application/exception/InvalidDataType.java
  src/main/java/com/yoyomo/domain/application/presentation/constant/ResponseMessage.java
  src/main/java/com/yoyomo/global/common/util/DateFormatter.java
  src/test/java/com/yoyomo/domain/application/domain/vo/ApplicationReplyTest.java
  src/test/java/com/yoyomo/domain/application/domain/vo/DataTypeTest.java
  src/test/java/com/yoyomo/domain/application/domain/vo/ReplyTest.java
Labels: 🧪 Test, 🛠️ Refactor

#397 CRA-TEMP main 머지
  .github/workflows/dev.yml
  .github/workflows/main.yml
  src/main/java/com/yoyomo/domain/application/application/dto/request/ApplicationImportRequest.java
  src/main/java/com/yoyomo/domain/application/application/dto/request/DataRequest.java
  src/main/java/com/yoyomo/domain/application/application/dto/request/QuestionRequest.java
  src/main/java/com/yoyomo/domain/application/application/dto/request/RespondentRequest.java
  src/main/java/com/yoyomo/domain/application/application/usecase/ApplicationImportUseCase.java
  src/main/java/com/yoyomo/domain/application/domain/entity/Application.java
  src/main/java/com/yoyomo/domain/application/domain/repository/ApplicationJdbcRepository.java
  src/main/java/com/yoyomo/domain/application/domain/service/AnswerSaveService.java
  src/main/java/com/yoyomo/domain/application/domain/service/ApplicationSaveService.java
  src/main/java/com/yoyomo/domain/application/domain/vo/Applicant.java
  src/main/java/com/yoyomo/domain/application/domain/vo/ApplicantInfo.java
  src/main/java/com/yoyomo/domain/application/domain/vo/ApplicationReply.java
  src/main/java/com/yoyomo/domain/application/domain/vo/DataType.java
  src/main/java/com/yoyomo/domain/application/domain/vo/Question.java
  src/main/java/com/yoyomo/domain/application/domain/vo/QuestionCategory.java
  src/main/java/com/yoyomo/domain/application/domain/vo/QuestionReply.java
  src/main/java/com/yoyomo/domain/application/domain/vo/Replies.java
  src/main/java/com/yoyomo/domain/application/domain/vo/Reply.java
  src/main/java/com/yoyomo/domain/application/exception/ApplicationReplySizeMismatchException.java
  src/main/java/com/yoyomo/domain/application/exception/BatchInsertFailException.java
  src/main/java/com/yoyomo/domain/application/exception/InvalidApplicantInfoException.java
  src/main/java/com/yoyomo/domain/application/exception/InvalidDataType.java
  src/main/java/com/yoyomo/domain/application/exception/InvalidDateFormat.java
  src/main/java/com/yoyomo/domain/application/exception/QuestionReplySizeMismatchException.java
  src/main/java/com/yoyomo/domain/application/presentation/ApplicationController.java
  src/main/java/com/yoyomo/domain/application/presentation/constant/ResponseMessage.java
  src/main/java/com/yoyomo/domain/item/domain/entity/Answer.java
  src/main/java/com/yoyomo/domain/item/domain/service/factory/AnswerCreationStrategy.java
  src/main/java/com/yoyomo/domain/item/domain/service/factory/ItemFactory.java
  src/main/java/com/yoyomo/domain/recruitment/application/usecase/RecruitmentManageUseCase.java
  src/main/java/com/yoyomo/domain/recruitment/domain/dto/RecruitmentCreateResponse.java
  src/main/java/com/yoyomo/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/com/yoyomo/domain/recruitment/presentation/RecruitmentController.java
  src/main/java/com/yoyomo/global/common/util/DateFormatter.java
  src/main/resources/application-local.yml
  src/test/java/com/yoyomo/domain/application/application/usecase/ApplicationImportUseCaseTest.java
  src/test/java/com/yoyomo/domain/application/domain/vo/ApplicationReplyTest.java
  src/test/java/com/yoyomo/domain/application/domain/vo/DataTypeTest.java
  src/test/java/com/yoyomo/domain/application/domain/vo/ReplyTest.java
  src/test/java/com/yoyomo/domain/fixture/CustomRepository.java
  src/test/java/com/yoyomo/domain/fixture/TestFixture.java
  src/test/resources/application-test.properties
Labels: ✨ Feature

#401 CRA-166 구글폼 import 날짜 포맷팅 오류 해결
  src/main/java/com/yoyomo/domain/application/application/dto/request/RespondentRequest.java
  src/main/java/com/yoyomo/domain/application/domain/service/ApplicationSaveService.java
  src/main/java/com/yoyomo/domain/application/domain/vo/QuestionReply.java
  src/test/java/com/yoyomo/domain/application/application/dto/request/ApplicationImportRequestTest.java
  src/test/java/com/yoyomo/domain/application/domain/vo/QuestionReplyTest.java
Labels: 🐞 Bug

#404 CRA-167 메인 머지
  src/main/java/com/yoyomo/domain/application/domain/repository/EvaluationMemoRepository.java
  src/main/java/com/yoyomo/domain/application/domain/repository/EvaluationRepository.java
  src/main/java/com/yoyomo/domain/application/domain/service/EvaluationDeleteService.java
  src/main/java/com/yoyomo/domain/application/domain/service/EvaluationMemoDeleteService.java
  src/main/java/com/yoyomo/domain/recruitment/application/usecase/RecruitmentManageUseCase.java
  src/test/java/com/yoyomo/domain/fixture/TestFixture.java
  src/test/java/com/yoyomo/domain/recruitment/application/usecase/RecruitmentManageUseCaseTest.java
Labels: 🐞 Bug, fix

#405 CRA-168 모니터링 구축
  build.gradle
  src/main/java/com/yoyomo/global/config/cors/CorsConfig.java
  src/main/java/com/yoyomo/global/config/logging/CustomRequestLoggingFilter.java
  src/main/java/com/yoyomo/global/config/mvc/WebMvcConfig.java
  src/main/resources/application.yml
  src/test/resources/application-test.properties
Labels: ✨ Feature

#408 CRA-168 메일 한도 제한 오류 및 수집 메트릭 설정 변경
  .github/workflows/main.yml
  src/main/java/com/yoyomo/global/config/redis/RedisConfig.java
  src/main/resources/application.yml
Labels: 🐞 Bug

#409 예외 메시지 수정
  src/main/java/com/yoyomo/domain/application/application/dto/request/EvaluationMemoRequest.java
  src/main/java/com/yoyomo/global/config/exception/GlobalExceptionHandler.java
Labels: 🐞 Bug

#415 CRA-171 같은 지원자가 동시에 두번 지원할 경우 지원되는 현상 수정
  src/main/java/com/yoyomo/domain/application/domain/entity/Application.java
  src/test/java/com/yoyomo/domain/application/domain/service/ApplicationSaveServiceTest.java
  src/test/java/com/yoyomo/domain/recruitment/application/usecase/RecruitmentManageUseCaseTest.java
Labels: 🐞 Bug, fix
