Repository Tough-Guy-Money-Party/Crayon-BE, pull requests merged in 2025-03, with the labels that each got.

#372 CRA-127 홍보페이지 업로드 로직 변경
  src/main/java/com/yoyomo/domain/landing/application/usecase/LandingGeneralManageUsecase.java
  src/main/java/com/yoyomo/global/config/redis/RedisConfig.java
  src/main/java/com/yoyomo/infra/aws/dto/LandingClientUploadEvent.java
  src/main/java/com/yoyomo/infra/aws/s3/service/S3Service.java
  src/main/java/com/yoyomo/infra/aws/s3/service/UploadEventListener.java
  src/main/java/com/yoyomo/infra/aws/usecase/DistributeUsecase.java
  src/main/java/com/yoyomo/infra/redis/RedisQueueService.java
  src/main/java/com/yoyomo/infra/redis/RedisQueueWorker.java
  src/main/java/com/yoyomo/infra/redis/service/RedisQueueService.java
  src/test/java/com/yoyomo/domain/DomainApplicationTest.java
  src/test/java/com/yoyomo/domain/application/domain/service/ApplicationSaveServiceTest.java
  src/test/java/com/yoyomo/domain/application/domain/service/InterviewRecordUpdateServiceTest.java
  src/test/java/com/yoyomo/domain/fixture/CustomRepository.java
  src/test/java/com/yoyomo/domain/fixture/TestFixture.java
Labels: ✨ Feature, fix

#380 CRA-156 지원자 수 조회 쿼리 변경 및 메일 템플릿 캐싱
  build.gradle
  src/main/java/com/yoyomo/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/com/yoyomo/domain/application/domain/service/ApplicationGetService.java
  src/main/java/com/yoyomo/domain/recruitment/domain/repository/ProcessRepository.java
  src/main/java/com/yoyomo/domain/recruitment/domain/service/ProcessGetService.java
  src/main/java/com/yoyomo/domain/template/application/dto/response/MailTemplateGetResponse.java
  src/main/java/com/yoyomo/domain/template/application/usecase/MailTemplateManageUseCase.java
  src/main/java/com/yoyomo/global/config/cache/CachingConfig.java
  src/test/java/com/yoyomo/domain/application/domain/service/InterviewRecordUpdateServiceTest.java
  src/test/java/com/yoyomo/domain/fixture/CustomRepository.java
Labels: ✨ Feature, 🛠️ Refactor

#382 CRA-158 테스트 코드 작성 / 모집 동시 수정 처리
  src/main/java/com/yoyomo/domain/application/domain/service/AnswerGetService.java
  src/main/java/com/yoyomo/domain/application/domain/service/ProcessResultSaveService.java
  src/main/java/com/yoyomo/domain/club/domain/service/ClubManagerSaveService.java
  src/main/java/com/yoyomo/domain/recruitment/domain/entity/Recruitment.java
  src/main/java/com/yoyomo/domain/recruitment/domain/service/RecruitmentUpdateService.java
  src/main/java/com/yoyomo/domain/recruitment/exception/ModifiedRecruitmentException.java
  src/main/java/com/yoyomo/domain/recruitment/presentation/constant/ResponseMessage.java
  src/test/java/com/yoyomo/domain/ApplicationTest.java
  src/test/java/com/yoyomo/domain/RepositoryTest.java
  src/test/java/com/yoyomo/domain/application/domain/repository/ApplicationRepositoryTest.java
  src/test/java/com/yoyomo/domain/application/domain/service/ApplicationGetServiceTest.java
  src/test/java/com/yoyomo/domain/application/domain/service/ApplicationSaveServiceTest.java
  src/test/java/com/yoyomo/domain/application/domain/service/InterviewRecordUpdateServiceTest.java
  src/test/java/com/yoyomo/domain/application/domain/service/ProcessResultGetServiceTest.java
  src/test/java/com/yoyomo/domain/club/domain/service/ClubManagerSaveServiceTest.java
  src/test/java/com/yoyomo/domain/fixture/TestFixture.java
  src/test/java/com/yoyomo/domain/recruitment/domain/service/RecruitmentUpdateServiceTest.java
Labels: ✨ Feature, 🧪 Test, 🛠️ Refactor

#384 CRA-155 홍보페이지 검증 추가 & 리펙토링
  src/main/java/com/yoyomo/domain/club/domain/service/ClubValidateService.java
  src/main/java/com/yoyomo/domain/landing/application/usecase/LandingGeneralManageUsecase.java
  src/main/java/com/yoyomo/domain/landing/domain/constant/ReservedSubDomain.java
  src/main/java/com/yoyomo/domain/landing/exception/InvalidFormatException.java
  src/main/java/com/yoyomo/domain/landing/presentation/constant/ResponseMessage.java
  src/main/java/com/yoyomo/global/common/aop/LoggingAspect.java
  src/main/java/com/yoyomo/global/common/util/SubdomainFormatter.java
  src/main/java/com/yoyomo/infra/aws/dto/LandingClientUploadEvent.java
  src/main/java/com/yoyomo/infra/aws/dto/LandingCreateEvent.java
  src/main/java/com/yoyomo/infra/aws/dto/LandingDeleteEvent.java
  src/main/java/com/yoyomo/infra/aws/exception/DeletionFailedException.java
  src/main/java/com/yoyomo/infra/aws/route53/service/Route53Service.java
  src/main/java/com/yoyomo/infra/aws/s3/service/DeleteLandingEventListener.java
  src/main/java/com/yoyomo/infra/aws/s3/service/LandingCreateEventListener.java
  src/main/java/com/yoyomo/infra/aws/s3/service/UploadEventListener.java
  src/main/java/com/yoyomo/infra/aws/usecase/DistributeUsecase.java
Labels: ✨ Feature, 🛠️ Refactor
