Repository Tough-Guy-Money-Party/Crayon-BE, pull requests merged in 2025-02, with the labels that each got.

#321 CRA-123 면접 프로세스에서 합격자 이동이 가능하게 변경
  src/main/java/com/yoyomo/domain/recruitment/domain/entity/Process.java
Labels: fix

#324 CRA-125 이미지 업로드 오류 수정
  src/main/java/com/yoyomo/infra/aws/s3/config/AwsS3Config.java
  src/main/java/com/yoyomo/infra/aws/s3/service/S3Service.java
Labels: 🐞 Bug, fix

#322 CRA-122 홍보페이지 성능 개선
  src/main/java/com/yoyomo/domain/club/exception/UnavailableSubdomainException.java
  src/main/java/com/yoyomo/global/common/aop/LoggingAspect.java
  src/main/java/com/yoyomo/global/config/async/AsyncConfig.java
  src/main/java/com/yoyomo/global/config/redis/RedisConfig.java
  src/main/java/com/yoyomo/infra/aws/usecase/DistributeUsecase.java
  src/main/java/com/yoyomo/infra/redis/RedisQueueService.java
  src/main/java/com/yoyomo/infra/redis/RedisQueueWorker.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: ✨ Feature

#327 CRA-128 리프레시 저장 수정
  src/main/java/com/yoyomo/domain/user/application/usecase/UserManageUsecase.java
Labels: 🐞 Bug, fix

#329 CRA-130 main 머지
  README.md
  src/main/java/com/yoyomo/domain/application/application/dto/response/ApplicationDetailResponse.java
  src/main/java/com/yoyomo/domain/application/application/dto/response/ApplicationListResponse.java
  src/main/java/com/yoyomo/domain/application/application/dto/response/EvaluationResponse.java
  src/main/java/com/yoyomo/domain/application/application/dto/response/EvaluationResponses.java
  src/main/java/com/yoyomo/domain/application/application/usecase/ApplicationManageUseCase.java
  src/main/java/com/yoyomo/domain/application/application/usecase/ApplyUseCase.java
  src/main/java/com/yoyomo/domain/application/application/usecase/EvaluationManageUseCase.java
  src/main/java/com/yoyomo/domain/application/domain/entity/ProcessResult.java
  src/main/java/com/yoyomo/domain/application/domain/entity/enums/Status.java
  src/main/java/com/yoyomo/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/com/yoyomo/domain/application/domain/repository/ProcessResultRepository.java
  src/main/java/com/yoyomo/domain/application/domain/service/ApplicationDeleteService.java
  src/main/java/com/yoyomo/domain/application/domain/service/ApplicationGetService.java
  src/main/java/com/yoyomo/domain/application/domain/service/ApplicationUpdateService.java
  src/main/java/com/yoyomo/domain/application/domain/service/ApplicationVerifyService.java
  src/main/java/com/yoyomo/domain/application/domain/service/ProcessResultGetService.java
  src/main/java/com/yoyomo/domain/application/domain/service/ProcessResultSaveService.java
  src/main/java/com/yoyomo/domain/application/exception/AlreadyAppliedException.java
  src/main/java/com/yoyomo/domain/application/presentation/constant/ResponseMessage.java
  src/main/java/com/yoyomo/domain/club/exception/UnavailableSubdomainException.java
  src/main/java/com/yoyomo/domain/form/application/usecase/FormManageUseCaseImpl.java
  src/main/java/com/yoyomo/domain/form/domain/repository/FormRepository.java
  src/main/java/com/yoyomo/domain/form/domain/service/FormGetService.java
  src/main/java/com/yoyomo/domain/mail/application/usecase/MailManageUseCaseImpl.java
  src/main/java/com/yoyomo/domain/recruitment/application/usecase/RecruitmentManageUseCase.java
  src/main/java/com/yoyomo/domain/recruitment/domain/entity/Process.java
  src/main/java/com/yoyomo/domain/recruitment/domain/repository/ProcessRepository.java
  src/main/java/com/yoyomo/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/com/yoyomo/domain/recruitment/domain/service/ProcessDeleteService.java
  src/main/java/com/yoyomo/domain/recruitment/domain/service/RecruitmentGetService.java
  src/main/java/com/yoyomo/domain/recruitment/presentation/RecruitmentController.java
  src/main/java/com/yoyomo/domain/user/application/usecase/UserManageUsecase.java
  src/main/java/com/yoyomo/domain/user/domain/entity/User.java
  src/main/java/com/yoyomo/domain/user/presentation/ManagerController.java
  src/main/java/com/yoyomo/domain/user/presentation/constant/ResponseMessage.java
  src/main/java/com/yoyomo/global/common/aop/LoggingAspect.java
  src/main/java/com/yoyomo/global/config/async/AsyncConfig.java
  src/main/java/com/yoyomo/global/config/jwt/JwtFilter.java
  src/main/java/com/yoyomo/global/config/jwt/JwtProvider.java
  src/main/java/com/yoyomo/global/config/redis/RedisConfig.java
  src/main/java/com/yoyomo/global/config/security/SecurityConfig.java
  src/main/java/com/yoyomo/infra/aws/s3/config/AwsS3Config.java
  src/main/java/com/yoyomo/infra/aws/s3/service/S3Service.java
  src/main/java/com/yoyomo/infra/aws/usecase/DistributeUsecase.java
  src/main/java/com/yoyomo/infra/redis/RedisQueueService.java
  src/main/java/com/yoyomo/infra/redis/RedisQueueWorker.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: ✨ Feature

#331 CRA-133 메일 커스텀 템플릿 미스매치 수정
  src/main/java/com/yoyomo/domain/mail/domain/entity/enums/CustomType.java
Labels: 🐞 Bug, fix

#334 CRA-134 test 서버 이전
  .github/workflows/dev.yml
  Dockerfile-dev
Labels: ✨ Feature, fix

#336 CRA-135 메일 면접일자 포맷 변경
  src/main/java/com/yoyomo/domain/mail/domain/entity/enums/CustomType.java
  src/main/java/com/yoyomo/global/common/util/DateFormatter.java
Labels: ✨ Feature, fix

#338 CRA-136 모집 수정 기능
  src/main/java/com/yoyomo/domain/club/application/usecase/ClubManagerUseCase.java
  src/main/java/com/yoyomo/domain/club/application/usecase/ClubReadUseCase.java
  src/main/java/com/yoyomo/domain/recruitment/application/dto/request/RecruitmentUpdateRequest.java
  src/main/java/com/yoyomo/domain/recruitment/application/usecase/RecruitmentManageUseCase.java
  src/main/java/com/yoyomo/domain/recruitment/domain/entity/Recruitment.java
  src/main/java/com/yoyomo/domain/recruitment/domain/service/RecruitmentUpdateService.java
  src/main/java/com/yoyomo/domain/recruitment/presentation/RecruitmentController.java
Labels: ✨ Feature, fix

#341 CRA-138 Evaluation process 필드 삭제
  src/main/java/com/yoyomo/domain/application/application/dto/request/EvaluationRequest.java
  src/main/java/com/yoyomo/domain/application/domain/entity/Evaluation.java
  src/main/java/com/yoyomo/domain/application/domain/repository/EvaluationRepository.java
  src/main/java/com/yoyomo/domain/application/domain/service/EvaluationGetService.java
  src/main/java/com/yoyomo/global/config/exception/GlobalExceptionHandler.java
  src/main/resources/application-prod.yml
Labels: 🐞 Bug

#343 CRA-140 합격자 이동 버그 수정
  src/main/java/com/yoyomo/domain/application/application/usecase/ApplicationManageUseCase.java
  src/main/java/com/yoyomo/domain/application/domain/repository/ProcessResultRepository.java
  src/main/java/com/yoyomo/domain/application/domain/service/ProcessResultGetService.java
Labels: 🐞 Bug, fix

#346 CRA-141 평가 메모 수정 및 삭제
  src/main/java/com/yoyomo/domain/application/application/usecase/EvaluationManageUseCase.java
  src/main/java/com/yoyomo/domain/application/domain/entity/EvaluationMemo.java
  src/main/java/com/yoyomo/domain/application/domain/repository/EvaluationMemoRepository.java
  src/main/java/com/yoyomo/domain/application/domain/service/EvaluationMemoUpdateService.java
  src/main/java/com/yoyomo/domain/application/exception/MemoDeleteException.java
  src/main/java/com/yoyomo/domain/application/exception/MemoUpdateException.java
  src/main/java/com/yoyomo/domain/application/presentation/EvaluationController.java
  src/main/java/com/yoyomo/domain/application/presentation/constant/ResponseMessage.java
Labels: ✨ Feature

#351 CRA-144 복제 기능 추가 & 메모 소유 여부 필드 추가
  src/main/java/com/yoyomo/domain/application/application/dto/response/EvaluationMemoResponse.java
  src/main/java/com/yoyomo/domain/application/application/dto/response/EvaluationResponses.java
  src/main/java/com/yoyomo/domain/application/application/usecase/EvaluationManageUseCase.java
  src/main/java/com/yoyomo/domain/form/application/usecase/FormManageUseCase.java
  src/main/java/com/yoyomo/domain/form/application/usecase/FormManageUseCaseImpl.java
  src/main/java/com/yoyomo/domain/form/domain/entity/Form.java
  src/main/java/com/yoyomo/domain/form/presentation/FormController.java
  src/main/java/com/yoyomo/domain/recruitment/application/usecase/RecruitmentManageUseCase.java
  src/main/java/com/yoyomo/domain/recruitment/domain/entity/Process.java
  src/main/java/com/yoyomo/domain/recruitment/domain/entity/Recruitment.java
  src/main/java/com/yoyomo/domain/recruitment/domain/service/ProcessSaveService.java
  src/main/java/com/yoyomo/domain/recruitment/domain/service/RecruitmentSaveService.java
  src/main/java/com/yoyomo/domain/recruitment/presentation/RecruitmentController.java
Labels: ✨ Feature, fix

#352 CRA-143 선택 항목 직접 입력 기능
  src/main/java/com/yoyomo/domain/item/application/dto/req/OptionRequest.java
  src/main/java/com/yoyomo/domain/item/application/dto/res/OptionResponse.java
  src/main/java/com/yoyomo/domain/item/application/mapper/ItemMapper.java
  src/main/java/com/yoyomo/domain/item/application/usecase/ItemManageUseCase.java
  src/main/java/com/yoyomo/domain/item/application/usecase/ItemManageUseCaseImpl.java
  src/main/java/com/yoyomo/domain/item/domain/entity/Option.java
Labels: ✨ Feature

#356 CRA-146 유저 정보 ArgumentResolver 반환타입 변경 및 CORS Config 추가
  src/main/java/com/yoyomo/global/common/resolver/CurrentUserArgumentResolver.java
  src/main/java/com/yoyomo/global/config/cors/CorsConfig.java
Labels: fix

#358 CRA-147 모집 상세에 시작 날짜 추가
  src/main/java/com/yoyomo/domain/recruitment/application/dto/response/RecruitmentResponseDTO.java
Labels: fix

#360 CRA-148 인증 정보 Interceptor 추가
  src/main/java/com/yoyomo/domain/form/presentation/FormController.java
  src/main/java/com/yoyomo/domain/recruitment/presentation/RecruitmentController.java
  src/main/java/com/yoyomo/global/common/annotation/RequiredAuth.java
  src/main/java/com/yoyomo/global/common/interceptor/AuthenticationInterceptor.java
  src/main/java/com/yoyomo/global/common/resolver/RequiredAuthArgumentResolver.java
  src/main/java/com/yoyomo/global/config/mvc/WebMvcConfig.java
  src/main/java/com/yoyomo/global/config/swagger/SwaggerConfig.java
Labels: ✨ Feature

#366 CRA-149 jwt 의존성 정리 및 검증 고도화
  build.gradle
  src/main/java/com/yoyomo/domain/user/application/usecase/UserManageUsecase.java
  src/main/java/com/yoyomo/global/common/interceptor/AuthenticationInterceptor.java
  src/main/java/com/yoyomo/global/common/resolver/CurrentUserArgumentResolver.java
  src/main/java/com/yoyomo/global/config/jwt/JwtProvider.java
  src/main/java/com/yoyomo/global/config/jwt/exception/InvalidTokenException.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/yoyomo/domain/application/domain/service/InterviewRecordUpdateServiceTest.java
Labels: 🛠️ Refactor

#371 CRA-151 request 로깅 필터
  src/main/java/com/yoyomo/global/config/logging/CustomRequestLoggingFilter.java
  src/main/java/com/yoyomo/global/config/logging/RequestLoggingFilterConfig.java
Labels: ✨ Feature

#369 CRA-150 지원자수 동시성 제어
  src/main/java/com/yoyomo/YoYoMoBeApplication.java
  src/main/java/com/yoyomo/domain/application/application/usecase/ApplyUseCase.java
  src/main/java/com/yoyomo/domain/application/domain/service/ApplicationSaveService.java
  src/main/java/com/yoyomo/domain/application/domain/service/ApplicationUpdateService.java
  src/main/java/com/yoyomo/domain/recruitment/domain/entity/Recruitment.java
  src/main/java/com/yoyomo/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/com/yoyomo/global/config/mongo/MongoConfig.java
  src/test/java/com/yoyomo/domain/application/domain/service/ApplicationSaveServiceTest.java
  src/test/java/com/yoyomo/fixture/CustomRepository.java
  src/test/java/com/yoyomo/fixture/TestFixture.java
  src/test/resources/application.yml
Labels: ✨ Feature, 🛠️ Refactor
