Repository Tough-Guy-Money-Party/Crayon-BE, pull requests merged in 2025-01, with the labels that each got.

#294 CRA-98 readme 작성
  README.md
Labels: 📜 Docs

#312 Fix/cra 109
  src/main/java/com/yoyomo/domain/application/application/dto/response/ApplicationDetailResponse.java
  src/main/java/com/yoyomo/domain/application/application/dto/response/ApplicationListResponse.java
  src/main/java/com/yoyomo/domain/application/application/dto/response/EvaluationResponse.java
  src/main/java/com/yoyomo/domain/application/application/dto/response/EvaluationResponses.java
  src/main/java/com/yoyomo/domain/application/application/usecase/ApplicationManageUseCase.java
  src/main/java/com/yoyomo/domain/application/application/usecase/EvaluationManageUseCase.java
  src/main/java/com/yoyomo/domain/application/domain/entity/ProcessResult.java
  src/main/java/com/yoyomo/domain/application/domain/entity/enums/Status.java
  src/main/java/com/yoyomo/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/com/yoyomo/domain/application/domain/repository/ProcessResultRepository.java
  src/main/java/com/yoyomo/domain/application/domain/service/ApplicationGetService.java
  src/main/java/com/yoyomo/domain/application/domain/service/ApplicationUpdateService.java
  src/main/java/com/yoyomo/domain/application/domain/service/ProcessResultGetService.java
  src/main/java/com/yoyomo/domain/application/domain/service/ProcessResultSaveService.java
  src/main/java/com/yoyomo/domain/mail/application/usecase/MailManageUseCaseImpl.java
Labels: 🐞 Bug, ✨ Feature

#314 CRA-113 모집 삭제 구현
  src/main/java/com/yoyomo/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/com/yoyomo/domain/application/domain/service/ApplicationDeleteService.java
  src/main/java/com/yoyomo/domain/form/application/usecase/FormManageUseCaseImpl.java
  src/main/java/com/yoyomo/domain/recruitment/application/usecase/RecruitmentManageUseCase.java
  src/main/java/com/yoyomo/domain/recruitment/domain/repository/ProcessRepository.java
  src/main/java/com/yoyomo/domain/recruitment/domain/service/ProcessDeleteService.java
  src/main/java/com/yoyomo/domain/recruitment/presentation/RecruitmentController.java
Labels: ✨ Feature, fix

#316 CRA-116 모집, 폼 조회시 내림차순으로 정렬
  src/main/java/com/yoyomo/domain/form/domain/repository/FormRepository.java
  src/main/java/com/yoyomo/domain/form/domain/service/FormGetService.java
  src/main/java/com/yoyomo/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/com/yoyomo/domain/recruitment/domain/service/RecruitmentGetService.java
Labels: fix

#318 CRA-111 토큰 재발급 API 구현 및 필터 경량화
  src/main/java/com/yoyomo/domain/user/application/usecase/UserManageUsecase.java
  src/main/java/com/yoyomo/domain/user/domain/entity/User.java
  src/main/java/com/yoyomo/domain/user/presentation/ManagerController.java
  src/main/java/com/yoyomo/domain/user/presentation/constant/ResponseMessage.java
  src/main/java/com/yoyomo/global/config/jwt/JwtFilter.java
  src/main/java/com/yoyomo/global/config/jwt/JwtProvider.java
  src/main/java/com/yoyomo/global/config/security/SecurityConfig.java
Labels: 🛠️ Refactor
